[package]
name = "lean-sys"
version = "0.1.0"
edition = "2021"
links = "leanshared"

[features]
small_allocator = []
default = ["small_allocator"]

[dependencies]
libc = "0.2"
memoffset = "0.6"
static_assertions = "1.1.0"